/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

/**
 *
 * @author Sebastián
 */
public class changeSize extends javax.swing.JFrame {

    /**
     * Creates new form changeSize
     */
    public changeSize() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xColumns = new javax.swing.JTextField();
        yRows = new javax.swing.JTextField();
        Columns = new javax.swing.JLabel();
        Rows = new javax.swing.JLabel();
        windowTitle = new javax.swing.JLabel();
        goMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xColumns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xColumnsActionPerformed(evt);
            }
        });
        jPanel1.add(xColumns, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 40, 130, -1));
        jPanel1.add(yRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 70, 130, -1));

        Columns.setText("Columnas:");
        jPanel1.add(Columns, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        Rows.setText("Filas:");
        jPanel1.add(Rows, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        windowTitle.setText("Ingrese los nuevos valores");
        jPanel1.add(windowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        goMenu.setText("Aceptar");
        goMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goMenuActionPerformed(evt);
            }
        });
        jPanel1.add(goMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goMenuActionPerformed

    private void xColumnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xColumnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xColumnsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeSize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeSize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Columns;
    private javax.swing.JLabel Rows;
    private javax.swing.JButton goMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel windowTitle;
    private javax.swing.JTextField xColumns;
    private javax.swing.JTextField yRows;
    // End of variables declaration//GEN-END:variables
}
