/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

/**
 *
 * @author Sebastián
 */
public class chooseMethod extends javax.swing.JFrame {

    /**
     * Creates new form selectSolution
     */
    public chooseMethod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        methodTitle = new javax.swing.JLabel();
        selectWallFollower = new javax.swing.JButton();
        selectDepthFirstS = new javax.swing.JButton();
        selectBreadthFirstS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        methodTitle.setText("Seleccione el metodo de solución");
        jPanel1.add(methodTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        selectWallFollower.setText("Wall Follower");
        selectWallFollower.setMaximumSize(new java.awt.Dimension(135, 22));
        selectWallFollower.setMinimumSize(new java.awt.Dimension(135, 22));
        selectWallFollower.setPreferredSize(new java.awt.Dimension(135, 22));
        selectWallFollower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectWallFollowerActionPerformed(evt);
            }
        });
        jPanel1.add(selectWallFollower, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        selectDepthFirstS.setText("Depth First Search");
        selectDepthFirstS.setMaximumSize(new java.awt.Dimension(135, 22));
        selectDepthFirstS.setMinimumSize(new java.awt.Dimension(135, 22));
        selectDepthFirstS.setPreferredSize(new java.awt.Dimension(135, 22));
        jPanel1.add(selectDepthFirstS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        selectBreadthFirstS.setText("Breadth First Search");
        jPanel1.add(selectBreadthFirstS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectWallFollowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectWallFollowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectWallFollowerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseMethod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel methodTitle;
    private javax.swing.JButton selectBreadthFirstS;
    private javax.swing.JButton selectDepthFirstS;
    private javax.swing.JButton selectWallFollower;
    // End of variables declaration//GEN-END:variables
}
