/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

/**
 *
 * @author Sebastián
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cosa = new javax.swing.JLabel();
        newLabyrinth = new javax.swing.JButton();
        solve = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        columnas = new javax.swing.JLabel();
        filas = new javax.swing.JLabel();
        tiempoTitle = new javax.swing.JLabel();
        xColumns = new javax.swing.JLabel();
        yRows = new javax.swing.JLabel();
        solTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cosa.setText("Laberinto aca");
        jPanel1.add(cosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        newLabyrinth.setText("Nuevo laberinto");
        newLabyrinth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLabyrinthActionPerformed(evt);
            }
        });
        jPanel1.add(newLabyrinth, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 40, 170, -1));

        solve.setText("Resolver");
        jPanel1.add(solve, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 370, -1));

        exit.setText("Terminar");
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        columnas.setText("Columnas:");
        jPanel1.add(columnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        filas.setText("Filas:");
        jPanel1.add(filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        tiempoTitle.setText("Tiempo de solución:");
        jPanel1.add(tiempoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        xColumns.setText("x");
        jPanel1.add(xColumns, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        yRows.setText("y");
        jPanel1.add(yRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        solTime.setText("time");
        jPanel1.add(solTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newLabyrinthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLabyrinthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newLabyrinthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel columnas;
    private javax.swing.JLabel cosa;
    private javax.swing.JButton exit;
    private javax.swing.JLabel filas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newLabyrinth;
    private javax.swing.JLabel solTime;
    private javax.swing.JButton solve;
    private javax.swing.JLabel tiempoTitle;
    private javax.swing.JLabel xColumns;
    private javax.swing.JLabel yRows;
    // End of variables declaration//GEN-END:variables
}
